Implements GitHub Actions
RockefellerArchiveCenter/docs-build pull request #243
Opened 2024-11-07 19:30 UTC by helrond

- Adds deploy and branch enforcement workflows. 
- Updates dependency workflow
- Removes Travis CI configs and build status from README

**NOTEs**:
- No test workflow was added since there are no unit tests for this repo
- A step to copy the theme config file was added to the deploy workflow
- The `BASENAME` variable does not appear to be needed in the deploy workflow, so I removed it.

2024-11-15 16:39 UTC, HaSistrunk reviewed
The styles deploy has an action to [invalidate the cloudfront cache](https://github.com/RockefellerArchiveCenter/styles/blob/861be22d0a0dbd3528a229fa4c5283c7d4f35f5f/.github/workflows/deploy_styleguide.yml#L57). Is that something we can do in this repo to address issue #185 ?

2024-11-15 16:39 UTC, HaSistrunk commented on .github/workflows/dependencies.yml
>          uses: actions/setup-python@v4
```suggestion
        uses: actions/setup-python@v5
```

2024-11-15 16:51 UTC, helrond commented
> The styles deploy has an action to [invalidate the cloudfront cache](https://github.com/RockefellerArchiveCenter/styles/blob/861be22d0a0dbd3528a229fa4c5283c7d4f35f5f/.github/workflows/deploy_styleguide.yml#L57). Is that something we can do in this repo to address issue #185 ?

Great call!

@p-galligan does the IAM user/role associated with this repo have permissions to create Cloudfront cache invalidations?

2024-11-15 18:55 UTC, p-galligan commented
> > The styles deploy has an action to [invalidate the cloudfront cache](https://github.com/RockefellerArchiveCenter/styles/blob/861be22d0a0dbd3528a229fa4c5283c7d4f35f5f/.github/workflows/deploy_styleguide.yml#L57). Is that something we can do in this repo to address issue #185 ?
> 
> Great call!
> 
> @p-galligan does the IAM user/role associated with this repo have permissions to create Cloudfront cache invalidations?

It did not, but I have changed up the role and added permissions to invalidate cloudfront cache now.

2024-11-15 18:59 UTC, ioduok approved these changes

2024-11-15 19:13 UTC, p-galligan approved these changes

2024-11-15 20:23 UTC, p-galligan requested changes

2024-11-15 20:23 UTC, p-galligan commented on .github/workflows/deploy.yml
> +          --function-name arn:aws:lambda:$AWS_REGION:$AWS_LAMBDA_ACCOUNT_ID:function:$LAMBDA_NAME
Actually just found two issues with this.

We need an if statement to check for the base (since we only want to deploy from prod images).

And `$AWS_LAMBDA_ACCOUNT_ID` should actually be `${{ secrets.AWS_ACCOUNT_ID }}`

2024-11-15 23:26 UTC, helrond commented
OK I added the conditional and changed the variable to the correct value. In looking at the Cloudfront invalidation - I realized this deploy is not actually building the site, so adding it to the deploy here won't do anything. Instead, that logic needs to be added to `update.py`.

2024-11-18 21:25 UTC, p-galligan approved these changes

2024-11-19 22:09 UTC, merged